# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  build:
    needs: checkout
    name: Build
    uses: ./.github/workflows/build-agent.yml
  workflow-test:
    needs: build
    runs-on: windows-2022
