name: Pull request checker
on:
  pull_request:
    branches: ["main"]

jobs:
  checker:
    runs-on: ubuntu-latest
    name: Pull request check
    env:
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check source branch name
        id: validate-name
        run: |
          echo $BRANCH_NAME
          if [[ ! $BRANCH_NAME =~ ^wip/ ]]; then
            echo "Error: Branch name must start with 'wip/'."
            exit 1
          fi

          CENTRAL_SECTION=$($BRANCH_NAME | cut -d'/' -f2)
          VALID_SECTIONS=("actions" "usermode" "kernelmode" "docs")

          if [[ ! " ${VALID_SECTIONS[@]} " =~ " ${CENTRAL_SECTION} " ]]; then
            echo "Error: Central section '$CENTRAL_SECTION' is not valid."
            exit 1
          fi
          
