name: Pytest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run pytest
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd ./PythonExtentions/
        python3 -m pip install -r requirements_development.txt
        pytest
    
    
