name: Pytest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
  run-pytest:
    needs: checkout
    runs-on: ubuntu-latest 
    steps:
    - name: Run pytest
      run: |
        ls
        python3 -m pip install -r PythonExtentions/requirements_development.txt
        pytest
    
    
