name: Offsets updater from a2x
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  job:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --global user.email "noreply@example.com"
          git config --global user.name "autotool-updateoffsets"
      - name: Create new wip branch
        run: |
          git checkout -b wip/offsets/auto-updater-${{ github.run_number }}
          git push -u origin wip/offsets/auto-updater-${{ github.run_number }}
      - name: Download required libs and push changes
        run: |
          LIBS=(buttons.hpp client_dll.hpp offsets.hpp)
          for lib in ${LIBS[@]}
          do
            curl https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/$lib > usermode/src/$lib
          done
          git add *
          git commit -m "OFFSET UPDATER -> updated offsets from remote repo"
          git push -u origin wip/offsets/auto-updater-${{ github.run_number }}
      - name: Open a pullrq to main
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --title "Offsets updated by automation" --body "Updated offsets from a2x repo" --base wip/offsets/auto-updater-${{ github.run_number }} --head main
      - name: Open a pullrq to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: | 
          gh pr create --title "Offsets updated by automation" --body "Updated offsets from a2x repo" --base wip/offsets/auto-updater-${{ github.run_number }} --head release
